// EVERY BUTTON SHOULD BE SAME.
// EVERY MODAL SHOULD BE BOTTOM MODAL SHEET.
// DATE PICKER SHOULD BE COMFORTABLE AND BEAUTIFUL.
// TRANSITIONS SHOULD BE BUTTER SMOOTH.
// TRY TO BUILD ATLEAST ONE CRUD SCREEN WITH CLASS COMPONENTS.
// NO INLINE STYLING WHAT SO EVER.
// UPDATE ALL THE PACKAGES AS PER NEW VERSIONS.
// READABILITY
// COMPATIBILITY
// MAINTANABILITY
// OPTIMIZED